import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import cron from 'node-cron';
import XLSX from 'xlsx';
import { fileURLToPath } from 'url';
import { initSchema, query, tx } from './db.js';
import { normalizeLogin, loginParts, setAuthCookie, clearAuthCookie, authFromRequest, randomToken, sha256 } from './auth.js';
import { sendMail, notifyOrderStatus, notifyAdminPaid } from './mail.js';
import { fetchSheetProducts } from './sheets.js';
import { getPaymentAdapter } from './payment-adapters/index.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(__dirname,'..');
const PUBLIC=path.join(ROOT,'public');
const UPLOADS=path.join(ROOT,'uploads');
fs.mkdirSync(UPLOADS,{recursive:true});
const seed=JSON.parse(fs.readFileSync(path.join(ROOT,'seed.json'),'utf8'));

if(!process.env.JWT_SECRET || process.env.JWT_SECRET.startsWith('CHANGE_ME')){
  if(process.env.NODE_ENV==='production') throw new Error('JWT_SECRET не настроен в .env');
  process.env.JWT_SECRET='dev-only-change-me';
}

const app=express();app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(compression());app.use(cookieParser());app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
app.use('/uploads',express.static(UPLOADS,{maxAge:'1d'}));

const authLimiter=rateLimit({windowMs:15*60*1000,limit:40,standardHeaders:'draft-7',legacyHeaders:false});
function currentAuth(req){return authFromRequest(req);}
function requireUser(req,res,next){const a=currentAuth(req);if(!a||a.role!=='user')return res.status(401).json({error:'Требуется вход'});req.auth=a;next();}
function requireAdmin(req,res,next){const a=currentAuth(req);if(!a||a.role!=='admin')return res.status(401).json({error:'Требуется вход администратора'});req.auth=a;next();}
function cleanSiteState(s){return {categories:Array.isArray(s?.categories)?s.categories:[],content:s?.content&&typeof s.content==='object'?s.content:{},menuSettings:s?.menuSettings&&typeof s.menuSettings==='object'?s.menuSettings:{},paymentSettings:s?.paymentSettings&&typeof s.paymentSettings==='object'?s.paymentSettings:{},media:s?.media&&typeof s.media==='object'?s.media:{}};}
function orderRow(r){return {id:r.id,number:r.number,user:r.user_login||'',createdAt:r.created_at,paidAt:r.paid_at,status:r.status,paymentStatus:r.payment_status,statusUpdatedAt:r.status_updated_at,total:r.total,items:r.items||[],contact:r.contact||{},recipientFio:r.recipient_fio||'',receive:r.receive,receiveText:r.receive_text,address:r.address||'',comment:r.comment||'',paymentModeAtCreation:r.payment_mode_at_creation,paymentProviderId:r.payment_provider_id||'',notifications:r.history||[],cancelReason:r.cancel_reason||''};}
async function getSite(){const {rows}=await query('SELECT categories,content,menu_settings,payment_settings,media FROM site_state WHERE id=1');if(!rows[0])return seed.site;return {categories:rows[0].categories,content:rows[0].content,menuSettings:rows[0].menu_settings,paymentSettings:rows[0].payment_settings,media:rows[0].media};}
async function getProductsGrouped(){const {rows}=await query('SELECT id,category_id,name,price,quantity,sort_order FROM products ORDER BY category_id,sort_order,name');const out={};for(const r of rows){(out[r.category_id]??=[]).push([r.name,r.price,r.quantity,r.id]);}return out;}
async function seedDatabase(){
  await initSchema();
  const s=cleanSiteState(seed.site);
  await query(`INSERT INTO site_state(id,categories,content,menu_settings,payment_settings,media) VALUES(1,$1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING`,[JSON.stringify(s.categories),JSON.stringify(s.content),JSON.stringify(s.menuSettings),JSON.stringify(s.paymentSettings),JSON.stringify(s.media)]);
  const {rows:[pc]}=await query('SELECT COUNT(*)::int n FROM products');
  if(!pc[0].n){for(const [cat,items] of Object.entries(seed.products)){for(let i=0;i<items.length;i++){const [name,price,qty]=items[i];const id=`${cat}_${i+1}`;await query('INSERT INTO products(id,category_id,name,price,quantity,sort_order,source) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING',[id,cat,name,price,qty,i,'seed']);}}}
  const email=normalizeLogin(process.env.ADMIN_EMAIL||'');const pass=String(process.env.ADMIN_PASSWORD||'');
  if(email&&pass && !pass.startsWith('CHANGE_ME')){const {rows}=await query('SELECT id FROM admin_users WHERE email=$1',[email]);if(!rows[0]){await query('INSERT INTO admin_users(id,email,password_hash) VALUES($1,$2,$3)',[crypto.randomUUID(),email,await bcrypt.hash(pass,12)]);console.log('Создан администратор',email);}}
  else if(process.env.NODE_ENV==='production'){console.warn('ВНИМАНИЕ: ADMIN_PASSWORD не задан. Вход в админку невозможен до настройки .env и перезапуска.');}
}

app.get('/api/health',(req,res)=>res.json({ok:true,time:new Date().toISOString()}));
app.get('/api/bootstrap',async(req,res,next)=>{try{const a=currentAuth(req),site=await getSite(),products=await getProductsGrouped();let orders=[];let user=null;let admin=false;if(a?.role==='user'){const {rows}=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id WHERE o.user_id=$1 ORDER BY o.created_at`,[a.id]);orders=rows.map(orderRow);user={login:a.login};}if(a?.role==='admin'){admin=true;const {rows}=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at`);orders=rows.map(orderRow);}res.json({site,products,user,admin,orders});}catch(e){next(e);}});

app.post('/api/auth/register',authLimiter,async(req,res,next)=>{try{const login=normalizeLogin(req.body.login),password=String(req.body.password||'');if(login.length<4||password.length<6)return res.status(400).json({error:'Проверьте логин и пароль'});const {email,phone}=loginParts(login);if(!email&&!phone)return res.status(400).json({error:'Введите e-mail или номер телефона'});const id=crypto.randomUUID(),hash=await bcrypt.hash(password,12);try{await query('INSERT INTO users(id,login,email,phone,password_hash) VALUES($1,$2,$3,$4,$5)',[id,login,email,phone,hash]);}catch(e){if(e.code==='23505')return res.status(409).json({error:'Такой аккаунт уже зарегистрирован'});throw e;}setAuthCookie(res,{role:'user',id,login});res.json({ok:true,user:{login},orders:[]});}catch(e){next(e);}});
app.post('/api/auth/login',authLimiter,async(req,res,next)=>{try{const login=normalizeLogin(req.body.login),password=String(req.body.password||'');const {rows}=await query('SELECT id,login,password_hash FROM users WHERE login=$1',[login]);const u=rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Неверный логин или пароль'});setAuthCookie(res,{role:'user',id:u.id,login:u.login});const os=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id WHERE o.user_id=$1 ORDER BY o.created_at`,[u.id]);res.json({ok:true,user:{login:u.login},orders:os.rows.map(orderRow)});}catch(e){next(e);}});
app.post('/api/auth/logout',(req,res)=>{clearAuthCookie(res);res.json({ok:true});});
app.post('/api/auth/forgot',authLimiter,async(req,res,next)=>{try{const email=normalizeLogin(req.body.email);const {rows}=await query('SELECT id,email FROM users WHERE email=$1',[email]);if(rows[0]){const raw=randomToken(),hash=sha256(raw),id=crypto.randomUUID();await query("INSERT INTO password_reset_tokens(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL '30 minutes')",[id,rows[0].id,hash]);const domain=process.env.DOMAIN||req.get('host');const link=`https://${domain}/?reset=${encodeURIComponent(raw)}`;await sendMail({to:email,subject:'КомпМастер — восстановление пароля',text:`Ссылка действует 30 минут: ${link}`});}res.json({ok:true,message:'Если такой e-mail зарегистрирован, ссылка отправлена.'});}catch(e){next(e);}});
app.post('/api/auth/reset',authLimiter,async(req,res,next)=>{try{const token=String(req.body.token||''),password=String(req.body.password||'');if(password.length<6)return res.status(400).json({error:'Пароль должен быть не короче 6 символов'});const hash=sha256(token);const {rows}=await query('SELECT * FROM password_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW()',[hash]);if(!rows[0])return res.status(400).json({error:'Ссылка недействительна или истекла'});await tx(async c=>{await c.query('UPDATE users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(password,12),rows[0].user_id]);await c.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE id=$1',[rows[0].id]);});res.json({ok:true});}catch(e){next(e);}});

app.post('/api/admin/login',authLimiter,async(req,res,next)=>{try{const email=normalizeLogin(req.body.email),password=String(req.body.password||'');const {rows}=await query('SELECT id,email,password_hash FROM admin_users WHERE email=$1',[email]);const a=rows[0];if(!a||!(await bcrypt.compare(password,a.password_hash)))return res.status(401).json({error:'Неверный e-mail или пароль'});setAuthCookie(res,{role:'admin',id:a.id,email:a.email});const os=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at`);res.json({ok:true,orders:os.rows.map(orderRow)});}catch(e){next(e);}});
app.post('/api/admin/logout',requireAdmin,(req,res)=>{clearAuthCookie(res);res.json({ok:true});});
app.post('/api/admin/change-password',requireAdmin,async(req,res,next)=>{try{const password=String(req.body.password||'');if(password.length<8)return res.status(400).json({error:'Минимум 8 символов'});await query('UPDATE admin_users SET password_hash=$1,updated_at=NOW() WHERE id=$2',[await bcrypt.hash(password,12),req.auth.id]);res.json({ok:true});}catch(e){next(e);}});
app.put('/api/admin/site-state',requireAdmin,async(req,res,next)=>{try{const s=cleanSiteState(req.body);await query(`UPDATE site_state SET categories=$1,content=$2,menu_settings=$3,payment_settings=$4,media=$5,updated_at=NOW() WHERE id=1`,[JSON.stringify(s.categories),JSON.stringify(s.content),JSON.stringify(s.menuSettings),JSON.stringify(s.paymentSettings),JSON.stringify(s.media)]);res.json({ok:true});}catch(e){next(e);}});

const upload=multer({dest:UPLOADS,limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||40)*1024*1024}});
function safeExt(file){const ext=path.extname(file.originalname).toLowerCase();return /^\.(png|jpe?g|webp|gif|mp4|webm|mov)$/.test(ext)?ext:'';}
app.post('/api/admin/upload',requireAdmin,upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'Файл не получен'});const kind=String(req.body.kind||'');const allowedImage=req.file.mimetype.startsWith('image/'),allowedVideo=req.file.mimetype.startsWith('video/');if(kind==='category'&&!allowedImage)throw new Error('Для категории нужно изображение');if(kind==='photo'&&!allowedImage)throw new Error('Нужно изображение');if(kind==='video'&&!allowedVideo)throw new Error('Нужно видео');const ext=safeExt(req.file)||'';const newName=`${Date.now()}-${crypto.randomBytes(6).toString('hex')}${ext}`;fs.renameSync(req.file.path,path.join(UPLOADS,newName));res.json({ok:true,url:`/uploads/${newName}`});}catch(e){if(req.file?.path&&fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);next(e);}});

app.post('/api/admin/import-xlsx/:categoryId',requireAdmin,upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'Файл не получен'});const wb=XLSX.readFile(req.file.path);const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});fs.unlinkSync(req.file.path);if(rows.length<2)return res.status(400).json({error:'В файле нет строк товара'});const h=rows[0].map(v=>String(v).trim().toLowerCase());const idx=(vars)=>h.findIndex(x=>vars.some(v=>x.includes(v)));const ni=idx(['наимен','назван','товар','name','модель']),pi=idx(['цена','price','стоим']),qi=idx(['колич','остат','доступ','qty']);if(ni<0||pi<0)return res.status(400).json({error:'Не найдены колонки названия/цены'});const items=rows.slice(1).map((r,i)=>({name:String(r[ni]||'').trim(),price:Math.round(Number(String(r[pi]||'').replace(/[^0-9.,]/g,'').replace(',','.'))),quantity:qi>=0?Math.max(0,Math.round(Number(String(r[qi]||'0').replace(/[^0-9]/g,''))||0)):0,sortOrder:i})).filter(x=>x.name&&Number.isFinite(x.price));await replaceCategoryProducts(req.params.categoryId,items,'xlsx');res.json({ok:true,count:items.length,products:await getProductsGrouped()});}catch(e){next(e);}});
async function replaceCategoryProducts(categoryId,items,source){await tx(async c=>{await c.query('DELETE FROM products WHERE category_id=$1',[categoryId]);for(let i=0;i<items.length;i++){const x=items[i],id=`${categoryId}_${crypto.createHash('sha1').update(x.name).digest('hex').slice(0,12)}`;await c.query('INSERT INTO products(id,category_id,name,price,quantity,sort_order,source,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,NOW())',[id,categoryId,x.name,x.price,x.quantity,i,source]);}});}
app.post('/api/admin/sync-sheet/:categoryId',requireAdmin,async(req,res,next)=>{try{const site=await getSite(),cat=(site.categories||[]).find(x=>x.id===req.params.categoryId);if(!cat?.sheet)return res.status(400).json({error:'У категории не указана Google Sheets'});const items=await fetchSheetProducts(cat.sheet);await replaceCategoryProducts(cat.id,items,'google_sheets');cat.updated=new Date().toLocaleDateString('ru-RU');await query('UPDATE site_state SET categories=$1,updated_at=NOW() WHERE id=1',[JSON.stringify(site.categories)]);res.json({ok:true,count:items.length,products:await getProductsGrouped(),categories:site.categories});}catch(e){next(e);}});

app.post('/api/orders',requireUser,async(req,res,next)=>{try{const body=req.body||{},requested=Array.isArray(body.items)?body.items:[];if(!requested.length)return res.status(400).json({error:'Корзина пуста'});const ids=requested.map(x=>String(x.id||''));const {rows}=await query('SELECT id,name,price,quantity,category_id FROM products WHERE id=ANY($1::text[])',[ids]);const byId=new Map(rows.map(r=>[r.id,r]));const items=[];let total=0;for(const x of requested){const p=byId.get(String(x.id||''));const qty=Math.max(1,Math.floor(Number(x.qty)||1));if(!p)return res.status(409).json({error:'Один из товаров больше недоступен. Обновите корзину.'});if(qty>p.quantity)return res.status(409).json({error:`Недостаточно товара: ${p.name}. Доступно ${p.quantity} шт.`});items.push({id:p.id,name:p.name,price:p.price,qty,categoryId:p.category_id});total+=p.price*qty;}
  const site=await getSite(),pm=site.paymentSettings||{};const contact=body.contact||{};if(!String(contact.fio||'').trim()||!String(contact.phone||'').trim()||!String(contact.email||'').trim())return res.status(400).json({error:'Заполните ФИО, телефон и e-mail'});const id=crypto.randomUUID(),created=new Date().toISOString();const history=[{at:created,text:'Заказ создан. Ожидает оплаты.'}];const order=await tx(async c=>{const ins=await c.query(`INSERT INTO orders(id,user_id,total,items,contact,recipient_fio,receive,receive_text,address,comment,payment_mode_at_creation,payment_provider_id,history) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[id,req.auth.id,total,JSON.stringify(items),JSON.stringify(contact),body.recipientFio||'',body.receive||'pickup',body.receiveText||'',body.address||'',body.comment||'',pm.mode==='automatic'?'automatic':'manual',pm.activeIntegrationId||'',JSON.stringify(history)]);const seq=ins.rows[0].seq,number=`01_${String(seq).padStart(6,'0')}`;const upd=await c.query('UPDATE orders SET number=$1 WHERE id=$2 RETURNING *',[number,id]);return upd.rows[0];});
  const u=await query('SELECT login FROM users WHERE id=$1',[req.auth.id]);const publicOrder=orderRow({...order,user_login:u.rows[0]?.login||req.auth.login});if(publicOrder.contact?.email)sendMail({to:publicOrder.contact.email,subject:`КомпМастер — заказ ${publicOrder.number} создан`,text:`Заказ ${publicOrder.number} создан. Сумма: ${publicOrder.total} ₽. Статус: Ожидает оплаты.`}).catch(console.error);res.json({ok:true,order:publicOrder});}catch(e){next(e);}});
app.get('/api/orders',requireUser,async(req,res,next)=>{try{const {rows}=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id WHERE o.user_id=$1 ORDER BY o.created_at`,[req.auth.id]);res.json({orders:rows.map(orderRow)});}catch(e){next(e);}});
app.patch('/api/orders/:id/address',requireUser,async(req,res,next)=>{try{const address=String(req.body.address||'').trim();if(!address)return res.status(400).json({error:'Введите адрес'});const {rows}=await query('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[req.params.id,req.auth.id]);const o=rows[0];if(!o)return res.status(404).json({error:'Заказ не найден'});if(!['Формируется заказ','В пути','Прибыл / готов к выдаче'].includes(o.status))return res.status(409).json({error:'На этом этапе адрес уже нельзя изменить'});const history=[...(o.history||[]),{at:new Date().toISOString(),text:'Адрес доставки изменён клиентом.'}];const upd=await query('UPDATE orders SET address=$1,history=$2 WHERE id=$3 RETURNING *',[address,JSON.stringify(history),o.id]);res.json({ok:true,order:orderRow({...upd.rows[0],user_login:req.auth.login})});}catch(e){next(e);}});

async function loadAdminOrder(id){const {rows}=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=$1`,[id]);return rows[0]?orderRow(rows[0]):null;}
app.get('/api/admin/orders',requireAdmin,async(req,res,next)=>{try{const {rows}=await query(`SELECT o.*,u.login user_login FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at`);res.json({orders:rows.map(orderRow)});}catch(e){next(e);}});
app.patch('/api/admin/orders/:id/status',requireAdmin,async(req,res,next)=>{try{const status=String(req.body.status||''),allowed=['Ожидает оплаты','Формируется заказ','В пути','Прибыл / готов к выдаче','В пути к клиенту','Завершён / выдан','Отменён'];if(!allowed.includes(status))return res.status(400).json({error:'Недопустимый статус'});const old=await loadAdminOrder(req.params.id);if(!old)return res.status(404).json({error:'Заказ не найден'});const at=new Date().toISOString(),history=[...(old.notifications||[]),{at,text:`Статус изменён администратором: ${old.status} → ${status}.`}];await query('UPDATE orders SET status=$1,status_updated_at=$2,history=$3 WHERE id=$4',[status,at,JSON.stringify(history),req.params.id]);const updated=await loadAdminOrder(req.params.id);await notifyOrderStatus(updated).catch(console.error);res.json({ok:true,order:updated});}catch(e){next(e);}});
app.post('/api/admin/orders/:id/cancel',requireAdmin,async(req,res,next)=>{try{const old=await loadAdminOrder(req.params.id);if(!old)return res.status(404).json({error:'Заказ не найден'});const reason=String(req.body.reason||''),at=new Date().toISOString(),history=[...(old.notifications||[]),{at,text:'Заказ отменён администратором.'+(reason?' Причина: '+reason:'')}];await query("UPDATE orders SET status='Отменён',cancel_reason=$1,status_updated_at=$2,history=$3 WHERE id=$4",[reason,at,JSON.stringify(history),req.params.id]);const updated=await loadAdminOrder(req.params.id);await notifyOrderStatus(updated).catch(console.error);res.json({ok:true,order:updated});}catch(e){next(e);}});
app.delete('/api/admin/orders/:id',requireAdmin,async(req,res,next)=>{try{await query('DELETE FROM orders WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){next(e);}});
app.post('/api/admin/orders/:id/confirm-payment',requireAdmin,async(req,res,next)=>{try{const old=await loadAdminOrder(req.params.id);if(!old)return res.status(404).json({error:'Заказ не найден'});if(old.paidAt||old.status==='Отменён')return res.status(409).json({error:'Оплата уже подтверждена или заказ отменён'});const at=new Date().toISOString(),history=[...(old.notifications||[]),{at,text:'Оплата подтверждена администратором. Статус: Формируется заказ.'}];await query("UPDATE orders SET paid_at=$1,payment_status='Оплачено',status='Формируется заказ',status_updated_at=$1,history=$2 WHERE id=$3",[at,JSON.stringify(history),req.params.id]);const updated=await loadAdminOrder(req.params.id);await Promise.allSettled([notifyOrderStatus(updated),notifyAdminPaid(updated)]);res.json({ok:true,order:updated});}catch(e){next(e);}});

app.post('/api/payments/:orderId/start',requireUser,async(req,res,next)=>{try{const {rows}=await query('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[req.params.orderId,req.auth.id]);const order=rows[0];if(!order)return res.status(404).json({error:'Заказ не найден'});const site=await getSite(),p=site.paymentSettings||{};if(p.mode!=='automatic')return res.status(409).json({error:'Включён ручной режим оплаты'});const active=(p.integrations||[]).find(x=>x.id===p.activeIntegrationId&&x.enabled!==false&&x.status==='server_ready');if(!active)return res.status(503).json({error:'Автоматическая оплата пока не настроена'});const adapter=getPaymentAdapter(active.adapterCode);if(!adapter)return res.status(503).json({error:'Серверный адаптер этой платёжной системы ещё не установлен'});const result=await adapter.createPayment({order,publicConfig:active});res.json(result);}catch(e){next(e);}});

cron.schedule('*/5 * * * *',async()=>{try{const {rows}=await query("SELECT id FROM orders WHERE status='Формируется заказ' AND paid_at IS NOT NULL AND paid_at <= NOW()-INTERVAL '35 hours'");for(const r of rows){const old=await loadAdminOrder(r.id);if(!old)continue;const at=new Date().toISOString(),history=[...(old.notifications||[]),{at,text:'Статус автоматически изменён: Формируется заказ → В пути.'}];await query("UPDATE orders SET status='В пути',status_updated_at=$1,history=$2 WHERE id=$3 AND status='Формируется заказ'",[at,JSON.stringify(history),r.id]);const updated=await loadAdminOrder(r.id);if(updated?.status==='В пути')await notifyOrderStatus(updated).catch(console.error);}}catch(e){console.error('35h cron',e);}});

app.use(express.static(PUBLIC,{maxAge:process.env.NODE_ENV==='production'?'1h':0}));
app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(path.join(PUBLIC,'index.html'));});
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Ошибка сервера'});});

await seedDatabase();
const port=Number(process.env.PORT||3000);app.listen(port,'0.0.0.0',()=>console.log(`КомпМастер server listening on :${port}`));
